#ifndef UI_SIMPLE_C_SIMPLE_CHECKBOX_SCRIPT_HPP
#define UI_SIMPLE_C_SIMPLE_CHECKBOX_SCRIPT_HPP

#include "ui/FrameScript.hpp"

#define NUM_SIMPLE_CHECKBOX_SCRIPT_METHODS 6

extern FrameScript_Method SimpleCheckboxMethods[NUM_SIMPLE_CHECKBOX_SCRIPT_METHODS];

#endif
