#ifndef UI_SIMPLE_C_SIMPLE_MODEL_FFX_SCRIPT_HPP
#define UI_SIMPLE_C_SIMPLE_MODEL_FFX_SCRIPT_HPP

#include "ui/FrameScript.hpp"

#define NUM_SIMPLE_MODEL_FFX_SCRIPT_METHODS 4

extern FrameScript_Method SimpleModelFFXMethods[NUM_SIMPLE_MODEL_FFX_SCRIPT_METHODS];

#endif
