#ifndef UI_SIMPLE_C_SIMPLE_STATUS_BAR_SCRIPT_HPP
#define UI_SIMPLE_C_SIMPLE_STATUS_BAR_SCRIPT_HPP

#include "ui/Types.hpp"

#define NUM_SIMPLE_STATUS_BAR_SCRIPT_METHODS 12

extern FrameScript_Method SimpleStatusBarMethods[NUM_SIMPLE_STATUS_BAR_SCRIPT_METHODS];

#endif
