#ifndef UI_SIMPLE_C_SIMPLE_SCROLL_FRAME_SCRIPT_HPP
#define UI_SIMPLE_C_SIMPLE_SCROLL_FRAME_SCRIPT_HPP

#include "ui/FrameScript.hpp"

#define NUM_SIMPLE_SCROLL_FRAME_SCRIPT_METHODS 9

extern FrameScript_Method SimpleScrollFrameMethods[NUM_SIMPLE_SCROLL_FRAME_SCRIPT_METHODS];

#endif
