#ifndef UI_SIMPLE_C_SIMPLE_FONT_STRING_SCRIPT_HPP
#define UI_SIMPLE_C_SIMPLE_FONT_STRING_SCRIPT_HPP

#include "ui/FrameScript.hpp"

#define NUM_SIMPLE_FONT_STRING_SCRIPT_METHODS 41

extern FrameScript_Method SimpleFontStringMethods[NUM_SIMPLE_FONT_STRING_SCRIPT_METHODS];

#endif
