#ifndef GLUE_TYPES_HPP
#define GLUE_TYPES_HPP

enum GLUESCRIPTEVENT {
    SET_GLUE_SCREEN                 = 0,
    START_GLUE_MUSIC                = 1,
    DISCONNECTED_FROM_SERVER        = 2,
    OPEN_STATUS_DIALOG              = 3,
    UPDATE_STATUS_DIALOG            = 4,
    CLOSE_STATUS_DIALOG             = 5,
    ADDON_LIST_UPDATE               = 6,
    CHARACTER_LIST_UPDATE           = 7,
    UPDATE_SELECTED_CHARACTER       = 8,
    OPEN_REALM_LIST                 = 9,
    GET_PREFERRED_REALM_INFO        = 10,
    UPDATE_SELECTED_RACE            = 11,
    SELECT_LAST_CHARACTER           = 12,
    SELECT_FIRST_CHARACTER          = 13,
    GLUE_SCREENSHOT_SUCCEEDED       = 14,
    GLUE_SCREENSHOT_FAILED          = 15,
    PATCH_UPDATE_PROGRESS           = 16,
    PATCH_DOWNLOADED                = 17,
    SUGGEST_REALM                   = 18,
    SUGGEST_REALM_WRONG_PVP         = 19,
    SUGGEST_REALM_WRONG_CATEGORY    = 20,
    SHOW_SERVER_ALERT               = 21,
    FRAMES_LOADED                   = 22,
    FORCE_RENAME_CHARACTER          = 23,
    FORCE_DECLINE_CHARACTER         = 24,
    SHOW_SURVEY_NOTIFICATION        = 25,
    PLAYER_ENTER_PIN                = 26,
    CLIENT_ACCOUNT_MISMATCH         = 27,
    PLAYER_ENTER_MATRIX             = 28,
    SCANDLL_ERROR                   = 29,
    SCANDLL_DOWNLOADING             = 30,
    SCANDLL_FINISHED                = 31,
    SERVER_SPLIT_NOTICE             = 32,
    TIMER_ALERT                     = 33,
    ACCOUNT_MESSAGES_AVAILABLE      = 34,
    ACCOUNT_MESSAGES_HEADERS_LOADED = 35,
    ACCOUNT_MESSAGES_BODY_LOADED    = 36,
    CLIENT_TRIAL                    = 37,
    PLAYER_ENTER_TOKEN              = 38,
    GAME_ACCOUNTS_UPDATED           = 39,
    CLIENT_CONVERTED                = 40,
    NUM_GLUESCRIPTEVENTS
};

#endif
