#ifndef UI_GAME_TYPES_HPP
#define UI_GAME_TYPES_HPP

enum SCRIPTEVENT {
    // TODO
    SCRIPT_ACTIONBAR_SLOT_CHANGED = 176,
    // TODO
    SCRIPT_PLAYER_LOGIN = 253,
    SCRIPT_PLAYER_LOGOUT = 254,
    SCRIPT_PLAYER_ENTERING_WORLD = 255,
    // TODO
    SCRIPT_CVAR_UPDATE = 298,
    // TODO
};

#endif
