// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_AREA_TABLE_REC_HPP
#define DB_REC_AREA_TABLE_REC_HPP

#include <cstdint>

class SFile;

class AreaTableRec {
    public:
        int32_t m_ID;
        int32_t m_continentID;
        int32_t m_parentAreaID;
        int32_t m_areaBit;
        int32_t m_flags;
        int32_t m_soundProviderPref;
        int32_t m_soundProviderPrefUnderwater;
        int32_t m_ambienceID;
        int32_t m_zoneMusic;
        int32_t m_introSound;
        int32_t m_explorationLevel;
        const char* m_areaName;
        int32_t m_factionGroupMask;
        int32_t m_liquidTypeID[4];
        float m_minElevation;
        float m_ambientMultiplier;
        int32_t m_lightID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
