// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/Cfg_ConfigsRec.hpp"
#include "util/Locale.hpp"
#include "util/SFile.hpp"

const char* Cfg_ConfigsRec::GetFilename() {
    return "DBFilesClient\\Cfg_Configs.dbc";
}

uint32_t Cfg_ConfigsRec::GetNumColumns() {
    return 4;
}

uint32_t Cfg_ConfigsRec::GetRowSize() {
    return 16;
}

bool Cfg_ConfigsRec::NeedIDAssigned() {
    return false;
}

int32_t Cfg_ConfigsRec::GetID() {
    return this->m_ID;
}

void Cfg_ConfigsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool Cfg_ConfigsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_realmType, sizeof(this->m_realmType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_playerKillingAllowed, sizeof(this->m_playerKillingAllowed), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_roleplaying, sizeof(this->m_roleplaying), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
