// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHARACTER_FACIAL_HAIR_STYLES_REC_HPP
#define DB_REC_CHARACTER_FACIAL_HAIR_STYLES_REC_HPP

#include <cstdint>

class SFile;

class CharacterFacialHairStylesRec {
    public:
        int32_t m_raceID;
        int32_t m_sexID;
        int32_t m_variationID;
        int32_t m_geoset[5];
        int32_t m_generatedID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
