// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_HAIR_GEOSETS_REC_HPP
#define DB_REC_CHAR_HAIR_GEOSETS_REC_HPP

#include <cstdint>

class SFile;

class CharHairGeosetsRec {
    public:
        int32_t m_ID;
        int32_t m_raceID;
        int32_t m_sexID;
        int32_t m_variationID;
        int32_t m_geosetID;
        int32_t m_showscalp;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
