// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_BASE_INFO_REC_HPP
#define DB_REC_CHAR_BASE_INFO_REC_HPP

#include <cstdint>

class SFile;

class CharBaseInfoRec {
    public:
        int8_t m_raceID;
        int8_t m_classID;
        int32_t m_generatedID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
