// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/CharBaseInfoRec.hpp"
#include "util/Locale.hpp"
#include "util/SFile.hpp"

const char* CharBaseInfoRec::GetFilename() {
    return "DBFilesClient\\CharBaseInfo.dbc";
}

uint32_t CharBaseInfoRec::GetNumColumns() {
    return 2;
}

uint32_t CharBaseInfoRec::GetRowSize() {
    return 2;
}

bool CharBaseInfoRec::NeedIDAssigned() {
    return true;
}

int32_t CharBaseInfoRec::GetID() {
    return this->m_generatedID;
}

void CharBaseInfoRec::SetID(int32_t id) {
    this->m_generatedID = id;
}

bool CharBaseInfoRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_raceID, sizeof(this->m_raceID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_classID, sizeof(this->m_classID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
