// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHR_CLASSES_REC_HPP
#define DB_REC_CHR_CLASSES_REC_HPP

#include <cstdint>

class SFile;

class ChrClassesRec {
    public:
        int32_t m_ID;
        int32_t m_damageBonusStat;
        int32_t m_displayPower;
        const char* m_petNameToken;
        const char* m_name;
        const char* m_nameFemale;
        const char* m_nameMale;
        const char* m_filename;
        int32_t m_spellClassSet;
        int32_t m_flags;
        int32_t m_cinematicSequenceID;
        int32_t m_requiredExpansion;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
