// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CREATURE_DISPLAY_INFO_REC_HPP
#define DB_REC_CREATURE_DISPLAY_INFO_REC_HPP

#include <cstdint>

class SFile;

class CreatureDisplayInfoRec {
    public:
        int32_t m_ID;
        int32_t m_modelID;
        int32_t m_soundID;
        int32_t m_extendedDisplayInfoID;
        float m_creatureModelScale;
        int32_t m_creatureModelAlpha;
        const char* m_textureVariation[3];
        const char* m_portraitTextureName;
        int32_t m_sizeClass;
        int32_t m_bloodID;
        int32_t m_npcsoundID;
        int32_t m_particleColorID;
        int32_t m_creatureGeosetData;
        int32_t m_objectEffectPackageID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
