// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CREATURE_DISPLAY_INFO_EXTRA_REC_HPP
#define DB_REC_CREATURE_DISPLAY_INFO_EXTRA_REC_HPP

#include <cstdint>

class SFile;

class CreatureDisplayInfoExtraRec {
    public:
        int32_t m_ID;
        int32_t m_displayRaceID;
        int32_t m_displaySexID;
        int32_t m_skinID;
        int32_t m_faceID;
        int32_t m_hairStyleID;
        int32_t m_hairColorID;
        int32_t m_facialHairID;
        int32_t m_npcitemDisplay[11];
        int32_t m_flags;
        const char* m_bakeName;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
