// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CREATURE_MODEL_DATA_REC_HPP
#define DB_REC_CREATURE_MODEL_DATA_REC_HPP

#include <cstdint>

class SFile;

class CreatureModelDataRec {
    public:
        int32_t m_ID;
        int32_t m_flags;
        const char* m_modelName;
        int32_t m_sizeClass;
        float m_modelScale;
        int32_t m_bloodID;
        int32_t m_footprintTextureID;
        float m_footprintTextureLength;
        float m_footprintTextureWidth;
        float m_footprintParticleScale;
        int32_t m_foleyMaterialID;
        int32_t m_footstepShakeSize;
        int32_t m_deathThudShakeSize;
        int32_t m_soundID;
        float m_collisionWidth;
        float m_collisionHeight;
        float m_mountHeight;
        float m_geoBoxMinX;
        float m_geoBoxMinY;
        float m_geoBoxMinZ;
        float m_geoBoxMaxX;
        float m_geoBoxMaxY;
        float m_geoBoxMaxZ;
        float m_worldEffectScale;
        float m_attachedEffectScale;
        float m_missileCollisionRadius;
        float m_missileCollisionPush;
        float m_missileCollisionRaise;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
