// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CREATURE_SOUND_DATA_REC_HPP
#define DB_REC_CREATURE_SOUND_DATA_REC_HPP

#include <cstdint>

class SFile;

class CreatureSoundDataRec {
    public:
        int32_t m_ID;
        int32_t m_soundExertionID;
        int32_t m_soundExertionCriticalID;
        int32_t m_soundInjuryID;
        int32_t m_soundInjuryCriticalID;
        int32_t m_soundInjuryCrushingBlowID;
        int32_t m_soundDeathID;
        int32_t m_soundStunID;
        int32_t m_soundStandID;
        int32_t m_soundFootstepID;
        int32_t m_soundAggroID;
        int32_t m_soundWingFlapID;
        int32_t m_soundWingGlideID;
        int32_t m_soundAlertID;
        int32_t m_soundFidget[5];
        int32_t m_customAttack[4];
        int32_t m_npcsoundID;
        int32_t m_loopSoundID;
        int32_t m_creatureImpactType;
        int32_t m_soundJumpStartID;
        int32_t m_soundJumpEndID;
        int32_t m_soundPetAttackID;
        int32_t m_soundPetOrderID;
        int32_t m_soundPetDismissID;
        float m_fidgetDelaySecondsMin;
        float m_fidgetDelaySecondsMax;
        int32_t m_birthSoundID;
        int32_t m_spellCastDirectedSoundID;
        int32_t m_submergeSoundID;
        int32_t m_submergedSoundID;
        int32_t m_creatureSoundDataIdpet;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
