// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_FACTION_TEMPLATE_REC_HPP
#define DB_REC_FACTION_TEMPLATE_REC_HPP

#include <cstdint>

class SFile;

class FactionTemplateRec {
    public:
        int32_t m_ID;
        int32_t m_faction;
        int32_t m_flags;
        int32_t m_factionGroup;
        int32_t m_friendGroup;
        int32_t m_enemyGroup;
        int32_t m_enemies[4];
        int32_t m_friend[4];

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
