// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/FactionTemplateRec.hpp"
#include "util/Locale.hpp"
#include "util/SFile.hpp"

const char* FactionTemplateRec::GetFilename() {
    return "DBFilesClient\\FactionTemplate.dbc";
}

uint32_t FactionTemplateRec::GetNumColumns() {
    return 14;
}

uint32_t FactionTemplateRec::GetRowSize() {
    return 56;
}

bool FactionTemplateRec::NeedIDAssigned() {
    return false;
}

int32_t FactionTemplateRec::GetID() {
    return this->m_ID;
}

void FactionTemplateRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool FactionTemplateRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_faction, sizeof(this->m_faction), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_factionGroup, sizeof(this->m_factionGroup), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_friendGroup, sizeof(this->m_friendGroup), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enemyGroup, sizeof(this->m_enemyGroup), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enemies[0], sizeof(m_enemies[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enemies[1], sizeof(m_enemies[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enemies[2], sizeof(m_enemies[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enemies[3], sizeof(m_enemies[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_friend[0], sizeof(m_friend[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_friend[1], sizeof(m_friend[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_friend[2], sizeof(m_friend[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_friend[3], sizeof(m_friend[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
