// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ItemVisualsRec.hpp"
#include "util/Locale.hpp"
#include "util/SFile.hpp"

const char* ItemVisualsRec::GetFilename() {
    return "DBFilesClient\\ItemVisuals.dbc";
}

uint32_t ItemVisualsRec::GetNumColumns() {
    return 6;
}

uint32_t ItemVisualsRec::GetRowSize() {
    return 24;
}

bool ItemVisualsRec::NeedIDAssigned() {
    return false;
}

int32_t ItemVisualsRec::GetID() {
    return this->m_ID;
}

void ItemVisualsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool ItemVisualsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_slot[0], sizeof(m_slot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_slot[1], sizeof(m_slot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_slot[2], sizeof(m_slot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_slot[3], sizeof(m_slot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_slot[4], sizeof(m_slot[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
