// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_DISPLAY_INFO_REC_HPP
#define DB_REC_ITEM_DISPLAY_INFO_REC_HPP

#include <cstdint>

class SFile;

class ItemDisplayInfoRec {
    public:
        int32_t m_ID;
        const char* m_modelName[2];
        const char* m_modelTexture[2];
        const char* m_inventoryIcon[2];
        int32_t m_geosetGroup[3];
        int32_t m_flags;
        int32_t m_spellVisualID;
        int32_t m_groupSoundIndex;
        int32_t m_helmetGeosetVisID[2];
        const char* m_texture[8];
        int32_t m_itemVisual;
        int32_t m_particleColorID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
