// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SOUND_ENTRIES_ADVANCED_REC_HPP
#define DB_REC_SOUND_ENTRIES_ADVANCED_REC_HPP

#include <cstdint>

class SFile;

class SoundEntriesAdvancedRec {
    public:
        int32_t m_ID;
        int32_t m_soundEntryID;
        float m_innerRadius2d;
        int32_t m_timeA;
        int32_t m_timeB;
        int32_t m_timeC;
        int32_t m_timeD;
        int32_t m_randomOffsetRange;
        int32_t m_usage;
        int32_t m_timeIntervalMin;
        int32_t m_timeIntervalMax;
        int32_t m_volumeSliderCategory;
        float m_duckToSfx;
        float m_duckToMusic;
        float m_duckToAmbience;
        float m_innerRadiusOfInfluence;
        float m_outerRadiusOfInfluence;
        int32_t m_timeToDuck;
        int32_t m_timeToUnduck;
        float m_insideAngle;
        float m_outsideAngle;
        float m_outsideVolume;
        float m_outerRadius2d;
        const char* m_name;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
