// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SOUND_ENTRIES_REC_HPP
#define DB_REC_SOUND_ENTRIES_REC_HPP

#include <cstdint>

class SFile;

class SoundEntriesRec {
    public:
        int32_t m_ID;
        int32_t m_soundType;
        const char* m_name;
        const char* m_file[10];
        int32_t m_freq[10];
        const char* m_directoryBase;
        float m_volumeFloat;
        int32_t m_flags;
        float m_minDistance;
        float m_distanceCutoff;
        int32_t m_eaxdef;
        int32_t m_soundEntriesAdvancedID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif
