// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/UnitBloodLevelsRec.hpp"
#include "util/Locale.hpp"
#include "util/SFile.hpp"

const char* UnitBloodLevelsRec::GetFilename() {
    return "DBFilesClient\\UnitBloodLevels.dbc";
}

uint32_t UnitBloodLevelsRec::GetNumColumns() {
    return 4;
}

uint32_t UnitBloodLevelsRec::GetRowSize() {
    return 16;
}

bool UnitBloodLevelsRec::NeedIDAssigned() {
    return false;
}

int32_t UnitBloodLevelsRec::GetID() {
    return this->m_ID;
}

void UnitBloodLevelsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool UnitBloodLevelsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_violencelevel[0], sizeof(m_violencelevel[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_violencelevel[1], sizeof(m_violencelevel[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_violencelevel[2], sizeof(m_violencelevel[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
