#ifndef CONSOLE_TYPES_HPP
#define CONSOLE_TYPES_HPP

enum COLOR_T {
    DEFAULT_COLOR,
    INPUT_COLOR,
    ECHO_COLOR,
    ERROR_COLOR,
    WARNING_COLOR,
    GLOBAL_COLOR,
    ADMIN_COLOR,
    HIGHLIGHT_COLOR,
    BACKGROUND_COLOR,
    NUM_COLORTYPES,
};

#endif
